---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kratos.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kratos.labels" . | indent 4 }}
  annotations:
    {{- with .Values.configmap.annotations }}
      {{- toYaml . | indent 4 }}
    {{- end }}
data:
  # Render the kratos config:
  "kratos.yaml": |
    {{- include "kratos.configmap" . | nindent 4 }}
  # Render the identity schemas to disk:
  {{- with .Values.kratos.identitySchemas }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
